In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
visa_df=pd.read_csv(r"C:\Users\jsamu\Documents\Naresh IT\Python\Visadataset.csv")

In [9]:
visa_df.shape

(25480, 12)

In [10]:
visa_df.size

305760

In [13]:
len(visa_df)

25480

In [14]:
visa_df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [15]:
visa_df.dtypes

case_id                   object
continent                 object
education_of_employee     object
has_job_experience        object
requires_job_training     object
no_of_employees            int64
yr_of_estab                int64
region_of_employment      object
prevailing_wage          float64
unit_of_wage              object
full_time_position        object
case_status               object
dtype: object

In [19]:
visa_df.isnull()

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,False,False,False,False,False,False,False,False,False,False,False,False
25476,False,False,False,False,False,False,False,False,False,False,False,False
25477,False,False,False,False,False,False,False,False,False,False,False,False
25478,False,False,False,False,False,False,False,False,False,False,False,False
25479,False,False,False,False,False,False,False,False,False,False,False,False

In [18]:
visa_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25480 entries, 0 to 25479
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   case_id                25480 non-null  object
 1   continent              25480 non-null  object
 2   education_of_employee  25480 non-null  object
 3   has_job_experience     25480 non-null  object
 4   requires_job_training  25480 non-null  object
 5   no_of_employees        25480 non-null  int64
 6   yr_of_estab            25480 non-null  int64
 7   region_of_employment   25480 non-null  object
 8   prevailing_wage        25480 non-null  float64
 9   unit_of_wage           25480 non-null  object
 10  full_time_position     25480 non-null  object
 11  case_status            25480 non-null  object
dtypes: float64(1), int64(2), object(9)
memory usage: 2.3+ MB

In [20]:
type(visa_df)

pandas.core.frame.DataFrame

In [21]:
type(visa_df.dtypes)

pandas.core.series.Series

- series looks like dataframe

- dataframe has column names matrix kind

- Series only index and its value

- Series like a dictionary key and values

In [22]:
visa_df.dtypes.keys()

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [26]:
visa_df.dtypes.values

array([dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('O'),
       dtype('int64'), dtype('int64'), dtype('O'), dtype('float64'),
       dtype('O'), dtype('O'), dtype('O')], dtype=object)

In [24]:
list(visa_df.dtypes.items())

[('case_id', dtype('O')),
 ('continent', dtype('O')),
 ('education_of_employee', dtype('O')),
 ('has_job_experience', dtype('O')),
 ('requires_job_training', dtype('O')),
 ('no_of_employees', dtype('int64')),
 ('yr_of_estab', dtype('int64')),
 ('region_of_employment', dtype('O')),
 ('prevailing_wage', dtype('float64')),
 ('unit_of_wage', dtype('O')),
 ('full_time_position', dtype('O')),
 ('case_status', dtype('O'))]

**Make a Dataframe**

In [27]:
pd.DataFrame(visa_df.dtypes)

                             0
case_id                 object
continent               object
education_of_employee   object
has_job_experience      object
requires_job_training   object
no_of_employees          int64
yr_of_estab              int64
region_of_employment    object
prevailing_wage        float64
unit_of_wage            object
full_time_position      object
case_status             object

In [28]:
keys=visa_df.dtypes.keys()
values=visa_df.dtypes.values
pd.DataFrame(zip(keys,values),
             columns=["Column name","Data type"])

              Column name Data type
0                 case_id    object
1               continent    object
2   education_of_employee    object
3      has_job_experience    object
4   requires_job_training    object
5         no_of_employees     int64
6             yr_of_estab     int64
7    region_of_employment    object
8         prevailing_wage   float64
9            unit_of_wage    object
10     full_time_position    object
11            case_status    object

- when we have a dictionary

- First makes in to keys and values seperate

- Then create a dataframe

**task-1:seperate categorical columns and numerical**

In [31]:
dict1={"A":1,
       "B":2,
       "a":3,
       "b":4}
for i,j in dict1.items():
    if i.isupper():
        print(j)

1
2

In [32]:
dict(visa_df.dtypes)
#iterate two i,j
# apply the condition
# if j=="object"
# append i in a list
# else
# append i in list

{'case_id': dtype('O'),
 'continent': dtype('O'),
 'education_of_employee': dtype('O'),
 'has_job_experience': dtype('O'),
 'requires_job_training': dtype('O'),
 'no_of_employees': dtype('int64'),
 'yr_of_estab': dtype('int64'),
 'region_of_employment': dtype('O'),
 'prevailing_wage': dtype('float64'),
 'unit_of_wage': dtype('O'),
 'full_time_position': dtype('O'),
 'case_status': dtype('O')}

In [36]:
dtypes=dict(visa_df.dtypes)
cat,num=[],[]
for i,j in dtypes.items():
    if j=="object":
        cat.append(i)
    else:
        num.append(i)
cat,num

(['case_id',
  'continent',
  'education_of_employee',
  'has_job_experience',
  'requires_job_training',
  'region_of_employment',
  'unit_of_wage',
  'full_time_position',
  'case_status'],
 ['no_of_employees', 'yr_of_estab', 'prevailing_wage'])

In [39]:
dtypes=dict(visa_df.dtypes)
cat=[i for i,j in dtypes.items() if j=="object"]
num=[i for i,j in dtypes.items() if j!="object"]
cat,num

(['case_id',
  'continent',
  'education_of_employee',
  'has_job_experience',
  'requires_job_training',
  'region_of_employment',
  'unit_of_wage',
  'full_time_position',
  'case_status'],
 ['no_of_employees', 'yr_of_estab', 'prevailing_wage'])

**select_dtypes**

In [41]:
cat=visa_df.select_dtypes(include="object").columns

In [42]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [43]:
num=visa_df.select_dtypes(exclude="object").columns

In [44]:
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [ ]:
# import the packages
# read the data
# selectedtypes

**Data selection**

- take

- loc

- iloc

In [45]:
# select 100,200,300 rows data
rows=[100,200,300]
visa_df.take(rows,axis=0)

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [46]:
visa_df.columns

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'no_of_employees', 'yr_of_estab',
       'region_of_employment', 'prevailing_wage', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [48]:
cols=[1,5]
visa_df.take(cols,axis=1).take(rows,axis=0)

    continent  no_of_employees
100      Asia             2227
200      Asia             3282
300      Asia             3268

- Manual counting index of columns

- At a time I can select rows and columns,we need to do two takes

**iloc**

- iloc[rows,columns]

- iloc[start:stop:step,start:stop:step]

In [49]:
visa_df.iloc[1:5,2:5]

  education_of_employee has_job_experience requires_job_training
1              Master's                  Y                     N
2            Bachelor's                  N                     Y
3            Bachelor's                  N                     N
4              Master's                  Y                     N

In [50]:
visa_df.iloc[1:5,5]

1     2412
2    44444
3       98
4     1082
Name: no_of_employees, dtype: int64

In [51]:
visa_df.iloc[4,2:5]

education_of_employee    Master's
has_job_experience              Y
requires_job_training           N
Name: 4, dtype: object

In [52]:
visa_df.iloc[1:5,[2,6,7]]

  education_of_employee  yr_of_estab region_of_employment
1              Master's         2002            Northeast
2            Bachelor's         2008                 West
3            Bachelor's         1897                 West
4              Master's         2005                South

In [53]:
visa_df.iloc[[100,200,300],2:5]

    education_of_employee has_job_experience requires_job_training
100              Master's                  Y                     N
200             Doctorate                  Y                     N
300              Master's                  Y                     N

In [54]:
visa_df.iloc[[100,200,300],[2,6,7]]

    education_of_employee  yr_of_estab region_of_employment
100              Master's         2007            Northeast
200             Doctorate         1979                 West
300              Master's         2012              Midwest

In [55]:
visa_df.iloc[100,5]

2227

In [56]:
visa_df.iloc[100]

case_id                    EZYV101
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2227
yr_of_estab                   2007
region_of_employment     Northeast
prevailing_wage           28243.79
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 100, dtype: object

In [57]:
visa_df.iloc[:,5]

0        14513
1         2412
2        44444
3           98
4         1082
         ...
25475     2601
25476     3274
25477     1121
25478     1918
25479     3195
Name: no_of_employees, Length: 25480, dtype: int64

In [58]:
visa_df.iloc[5,:]

case_id                     EZYV06
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2339
yr_of_estab                   2012
region_of_employment         South
prevailing_wage           78252.14
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 5, dtype: object

In [60]:
visa_df.iloc[:,[5]]

       no_of_employees
0                14513
1                 2412
2                44444
3                   98
4                 1082
...                ...
25475             2601
25476             3274
25477             1121
25478             1918
25479             3195

[25480 rows x 1 columns]

In [ ]:
visa_df.iloc[:,5]  # series
visa_df.iloc[:,[5]]    #df

In [61]:
visa_df.iloc[:,"no_of_employees"]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

**take**

- Manual counting

-At a time we can not select rows and columns

**iloc**

- Manual counting

**loc**

In [62]:
visa_df.loc[:,"no_of_employees"]

0        14513
1         2412
2        44444
3           98
4         1082
         ...
25475     2601
25476     3274
25477     1121
25478     1918
25479     3195
Name: no_of_employees, Length: 25480, dtype: int64

In [69]:
visa_df.loc[1:5,"no_of_employees"]

1     2412
2    44444
3       98
4     1082
5     2339
Name: no_of_employees, dtype: int64

In [70]:
visa_df.loc[4,2:"no_of_employees"]

TypeError: cannot do slice indexing on Index with these indexers [2] of type int

In [71]:
visa_df.loc[1:5,["no_of_employees"]]

   no_of_employees
1             2412
2            44444
3               98
4             1082
5             2339

In [66]:
visa_df.loc[[100,200,300],:]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
100,EZYV101,Asia,Master's,Y,N,2227,2007,Northeast,28243.79,Year,Y,Certified
200,EZYV201,Asia,Doctorate,Y,N,3282,1979,West,74441.11,Year,Y,Certified
300,EZYV301,Asia,Master's,Y,N,3268,2012,Midwest,101371.21,Year,Y,Certified

In [72]:
visa_df.loc[[100,200,300],["no_of_employees"]]

     no_of_employees
100             2227
200             3282
300             3268

In [73]:
visa_df.loc[100,"no_of_employees"]

2227

In [74]:
visa_df.loc[100]

case_id                    EZYV101
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2227
yr_of_estab                   2007
region_of_employment     Northeast
prevailing_wage           28243.79
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 100, dtype: object

In [76]:
visa_df.loc[:,"no_of_employees"]

0        14513
1         2412
2        44444
3           98
4         1082
         ...
25475     2601
25476     3274
25477     1121
25478     1918
25479     3195
Name: no_of_employees, Length: 25480, dtype: int64

In [77]:
visa_df.loc[5,:]

case_id                     EZYV06
continent                     Asia
education_of_employee     Master's
has_job_experience               Y
requires_job_training            N
no_of_employees               2339
yr_of_estab                   2012
region_of_employment         South
prevailing_wage           78252.14
unit_of_wage                  Year
full_time_position               Y
case_status              Certified
Name: 5, dtype: object