- we perform the numerical analysis

    - statistical measures

    - emperical rule

    - histigram

    - box plot

- outlier analysis

    - treat the outliers

- scatter plots

    - Heat map

- Encode: convert cat to numerical

    - map

    - LabelEncoder

    - OneHotEncoder

    - np.where

**Standardization**

- Standardization also called as Z-score

- Z-score values ranges from -3 to 3

    -  z=x-u/sigma

In [2]:
# Read the data
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

file_path=r"C:\Users\jsamu\Documents\Naresh IT\Python\Visadataset.csv"
visa_df=pd.read_csv(file_path)
visa_df

cat_cols=visa_df.select_dtypes(include="object").columns
num_cols=visa_df.select_dtypes(exclude="object").columns
cat_cols,num_cols

(Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
        'requires_job_training', 'region_of_employment', 'unit_of_wage',
        'full_time_position', 'case_status'],
       dtype='object'),
 Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object'))

In [ ]:
# step-1: take the prevailage wage column
# step-2: mean of wage
# step-3: sd of wage
# step-4: step1-step-2
# step-5: step4/step3

In [3]:
wage_data=visa_df["prevailing_wage"]
wage_mean=wage_data.mean()
wage_sd=wage_data.std()
NR=wage_data-wage_mean
data1=NR/wage_sd
visa_df["prevailing_wage_Z"]=data1

In [4]:
visa_df[["prevailing_wage","prevailing_wage_Z"]]

       prevailing_wage  prevailing_wage_Z
0             592.2029          -1.398510
1           83425.6500           0.169832
2          122996.8600           0.919060
3           83434.0300           0.169991
4          149907.3900           1.428576
...                ...                ...
25475       77092.5700           0.049923
25476      279174.7900           3.876083
25477      146298.8500           1.360253
25478       86154.7700           0.221504
25479       70876.9100          -0.067762

[25480 rows x 2 columns]

**StandardScalar**

- sklearn

    - preprocessing

        - StandardScalar

**Note**
- StandardScalar takes input as DataFrame not series

In [6]:
visa_df["prevailing_wage"]

0           592.2029
1         83425.6500
2        122996.8600
3         83434.0300
4        149907.3900
            ...
25475     77092.5700
25476    279174.7900
25477    146298.8500
25478     86154.7700
25479     70876.9100
Name: prevailing_wage, Length: 25480, dtype: float64

In [16]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit_transform(visa_df[["prevailing_wage"]])

array([[-1.39853722],
       [ 0.1698353 ],
       [ 0.91907852],
       ...,
       [ 1.36027953],
       [ 0.22150859],
       [-0.06776315]])

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit_transform(visa_df["prevailing_wage"])

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [18]:
wage_data_reshaped=visa_df["prevailing_wage"].values.reshape(-1,1)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit_transform(wage_data_reshaped)

array([[-1.39853722],
       [ 0.1698353 ],
       [ 0.91907852],
       ...,
       [ 1.36027953],
       [ 0.22150859],
       [-0.06776315]])

**Check point-1**

**idxmax and idxmin**

In [19]:
visa_df["prevailing_wage"].idxmax()==visa_df["prevailing_wage_Z"].idxmax()

True

In [21]:
visa_df["prevailing_wage"].idxmin()==visa_df["prevailing_wage_Z"].idxmin()

True

In [22]:
max_id=visa_df["prevailing_wage"].idxmax()
min_id=visa_df["prevailing_wage"].idxmin()
visa_df.iloc[[max_id,min_id]]

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status,prevailing_wage_Z
21077,EZYV21078,Asia,High School,N,N,442,2006,Midwest,319210.2700,Year,Y,Denied,4.634102
20575,EZYV20576,North America,Master's,N,N,1552,2004,Northeast,2.1367,Hour,Y,Certified,-1.409682

**check-point-2**

- we developed the code into two ways

- from scrach and using package

In [23]:
wage_data=visa_df["prevailing_wage"]
wage_mean=wage_data.mean()
wage_sd=wage_data.std()
NR=wage_data-wage_mean
data1=NR/wage_sd
visa_df["prevailing_wage_Z"]=data1


from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
visa_df["prevailing_wage_SS"]=sc.fit_transform(visa_df[["prevailing_wage"]])

visa_df[["prevailing_wage_Z","prevailing_wage_SS"]]

       prevailing_wage_Z  prevailing_wage_SS
0              -1.398510           -1.398537
1               0.169832            0.169835
2               0.919060            0.919079
3               0.169991            0.169994
4               1.428576            1.428604
...                  ...                 ...
25475           0.049923            0.049924
25476           3.876083            3.876159
25477           1.360253            1.360280
25478           0.221504            0.221509
25479          -0.067762           -0.067763

[25480 rows x 2 columns]

**Normalization**

- Normalization also called as MinMaxScalar

- The values ranges from 0 to 1

- X= x-xmin/xmax-xmin

In [ ]:
# step-1: read the prevailing wage data
# step-2: caliculate wage min
# step-3: calculate wage max data
# step-4: Nr=step1-step2
# step-5: Dr= step3-step2
# step-6: Nr/Dr

####################################
sklearn preprocessing MinMaxScalar

In [29]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
wage_mms=mms.fit_transform(visa_df[["prevailing_wage"]])

In [30]:
wage_mms.max()

0.9999999999999999

In [31]:
wage_mms.min()

0.0