############# EDA ####################
1.Data preprocess
    - missing value analysis
    - data types mismatch
2.Data analysis
    - Categorical
    - Numerical
    - Bi variate
    - Multivariate
    - Outlier analysis
3.Feature engineering
    - Impute the outliers
    - ML needs number Eng to Numbers : Encoding
    - Scaling : Standardization and Normalization
    - Transformation : Convert into Normal distribution

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

visa_df=pd.read_csv(r"C:\Users\jsamu\Documents\Naresh IT\Python\Visadataset.csv")
cat=visa_df.select_dtypes(include="object").columns
num=visa_df.select_dtypes(exclude="object").columns

In [2]:
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [3]:
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

**case_status**

In [5]:
# step-1: find how many unique labels are there
visa_df["case_status"].unique()

array(['Denied', 'Certified'], dtype=object)

In [7]:
# step-2: Create a dictionary by assign a values to the labels
#      follow the alphabet order
#      python index start with zero

d={"Certfied":0,"Denied":1}
d       # think how create a dictionary automatically

{'Certfied': 0, 'Denied': 1}

In [9]:
visa_df["case_status"]=visa_df["case_status"].map(d)

In [10]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1.0
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,NaN
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1.0
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1.0
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,NaN
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,NaN
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,NaN
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,NaN
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,NaN

In [11]:
visa_df=pd.read_csv(r"C:\Users\jsamu\Documents\Naresh IT\Python\Visadataset.csv")

In [12]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [13]:
visa_df["case_status"].unique()

array(['Denied', 'Certified'], dtype=object)

In [14]:
d={"Certfied":0,"Denied":1}
d       # think how create a dictiona

{'Certfied': 0, 'Denied': 1}

In [15]:
visa_df["case_status"]=visa_df["case_status"].map(d)

In [16]:
visa_df["case_status"]

0        1.0
1        NaN
2        1.0
3        1.0
4        NaN
        ...
25475    NaN
25476    NaN
25477    NaN
25478    NaN
25479    NaN
Name: case_status, Length: 25480, dtype: float64

In [17]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1.0
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,NaN
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1.0
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1.0
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,NaN
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,NaN
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,NaN
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,NaN
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,NaN

In [18]:
visa_df=pd.read_csv(r"C:\Users\jsamu\Documents\Naresh IT\Python\Visadataset.csv")

In [19]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [59]:
visa_df["continent"].unique()

array([0], dtype=int64)

In [60]:
continents=len(visa_df["continent"].unique())
continents

1

In [61]:
labels=visa_df["continent"].unique()
d={}
for i in range(len(labels)):
    d[labels[i]]=i
d

{0: 0}

In [62]:
d={labels[i]:i for i in range(len(labels))}

In [63]:
visa_df["continent"]=visa_df["continent"].map(d)

In [64]:
visa_df["continent"]

0        0
1        0
2        0
3        0
4        0
        ..
25475    0
25476    0
25477    0
25478    0
25479    0
Name: continent, Length: 25480, dtype: int64

In [65]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,0,0,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,0,1,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,0,2,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,0,2,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,1,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,0,2,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,0,0,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,0,1,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,0,1,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,0,2,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [47]:
visa_df=pd.read_csv(r"C:\Users\jsamu\Documents\Naresh IT\Python\Visadataset.csv")
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [48]:
visa_df["education_of_employee"].unique()

array(['High School', "Master's", "Bachelor's", 'Doctorate'], dtype=object)

In [49]:
labels=visa_df["education_of_employee"].unique()
d={labels[i]:i for i in range(len(labels))}
d

{'High School': 0, "Master's": 1, "Bachelor's": 2, 'Doctorate': 3}

In [51]:
visa_df["education_of_employee"]=visa_df["education_of_employee"].map(d)

In [52]:
visa_df["education_of_employee"]

0        0
1        1
2        2
3        2
4        1
        ..
25475    2
25476    0
25477    1
25478    1
25479    2
Name: education_of_employee, Length: 25480, dtype: int64

In [53]:
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,NaN,0,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,NaN,1,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,NaN,2,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,NaN,2,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,NaN,1,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,NaN,2,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,NaN,0,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,NaN,1,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,NaN,1,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,NaN,2,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

- sklearn aka scikit-learn

   - preprocessing

       - LabelEncoder


- step1: Import the module

- step2: save the module

- step3: apply fit_trandform

     - fit means create a dictionary
     - trandform means apply dictionary so that data will be transformed

In [70]:
visa_df=pd.read_csv(r"C:\Users\jsamu\Documents\Naresh IT\Python\Visadataset.csv")

In [71]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df["case_status"]=le.fit_transform(visa_df["case_status"])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [73]:
visa_df=pd.read_csv(r"C:\Users\jsamu\Documents\Naresh IT\Python\Visadataset.csv")

In [74]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
visa_df["continent"]=le.fit_transform(visa_df["continent"])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [76]:
le.inverse_transform(visa_df["continent"])[:5]

array(['Asia', 'Asia', 'Asia', 'Asia', 'Africa'], dtype=object)

In [77]:
visa_df=pd.read_csv(r"C:\Users\jsamu\Documents\Naresh IT\Python\Visadataset.csv")
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for i in cat[1:]:
    visa_df[i]=le.fit_transform(visa_df[i])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**OneHotEncoder**

- OneHot means at a time one will be ON(1) another will be OFF(0)

|case_status|case_status_Denied|case_status_Certified|
|-|-|-|
|Denied|1|0|
|Certified|0|1|

In [78]:
visa_df=pd.read_csv(r"C:\Users\jsamu\Documents\Naresh IT\Python\Visadataset.csv")

In [81]:
pd.get_dummies(visa_df,columns=cat[1:],dtype=int)

,case_id,no_of_employees,yr_of_estab,prevailing_wage,continent_Africa,continent_Asia,continent_Europe,continent_North America,continent_Oceania,continent_South America,...,region_of_employment_South,region_of_employment_West,unit_of_wage_Hour,unit_of_wage_Month,unit_of_wage_Week,unit_of_wage_Year,full_time_position_N,full_time_position_Y,case_status_Certified,case_status_Denied
0,EZYV01,14513,2007,592.2029,0,1,0,0,0,0,...,0,1,1,0,0,0,0,1,0,1
1,EZYV02,2412,2002,83425.6500,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
2,EZYV03,44444,2008,122996.8600,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
3,EZYV04,98,1897,83434.0300,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
4,EZYV05,1082,2005,149907.3900,1,0,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,2601,2008,77092.5700,0,1,0,0,0,0,...,1,0,0,0,0,1,0,1,1,0
25476,EZYV25477,3274,2006,279174.7900,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0
25477,EZYV25478,1121,1910,146298.8500,0,1,0,0,0,0,...,1,0,0,0,0,1,1,0,1,0
25478,EZYV25479,1918,1887,86154.7700,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,1,0
25479,EZYV25480,3195,1960,70876.9100,0,1,0,0,0,0,...,0,0,0,0,0,1,0,1,1,0

**LabelEncoder vs OneHotEncoder**

- Generally we dont want a relation between input column

- we need both input columns are **not correlated** each other

- we need both input columns are **independent(x,y)** each other

- we need both input columns are **perpendicular** each other

- we need both input columns are **Orthogonal** each other

- we need both input columns are **90 degrees phase shift** each other

- OneHotEncoder will achieve above

- But OneHotEncoder creates new columns

    - columns are increase means dimensions are increase

    - More dimensions data need more processing time

    - More dimension data need more infra

    - This is called **Curse of Dimensionality**